use centraldb;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    phone VARCHAR2(15),
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'user' NOT NULL,
    status VARCHAR2(20) DEFAULT 'active' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reset_token VARCHAR2(255),
    reset_expires TIMESTAMP,
    CONSTRAINT chk_users_role 
        CHECK (role IN ('user', 'admin', 'super_admin')),
    CONSTRAINT chk_users_status 
        CHECK (status IN ('active', 'inactive', 'banned'))
);

CREATE TABLE users (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    phone VARCHAR2(15),

    password VARCHAR2(255) NOT NULL,

    role VARCHAR2(50) DEFAULT 'user' NOT NULL,
    status VARCHAR2(20) DEFAULT 'active' NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    reset_token VARCHAR2(255),
    reset_expires TIMESTAMP,

    otp VARCHAR2(10),
    otp_expires TIMESTAMP,

    refresh_token VARCHAR2(500),

    is_verified NUMBER(1) DEFAULT 0
);


//////////////////////////////////
CREATE TABLE trusted_devices (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  user_email VARCHAR2(255),
  device_token VARCHAR2(255),
  user_agent VARCHAR2(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP
);

/////////////////////////////