use centraldb;

CREATE TABLE
    users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2 (100) NOT NULL,
        email VARCHAR2 (150) UNIQUE NOT NULL,
        phone VARCHAR2 (15),
        password VARCHAR2 (255) NOT NULL,
        role VARCHAR2 (50) DEFAULT 'user' NOT NULL,
        status VARCHAR2 (20) DEFAULT 'active' NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        reset_token VARCHAR2 (255),
        reset_expires TIMESTAMP,
        CONSTRAINT chk_users_role CHECK (role IN ('user', 'admin', 'super_admin')),
        CONSTRAINT chk_users_status CHECK (status IN ('active', 'inactive', 'banned'))
    );

CREATE TABLE
    users (
        id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name VARCHAR2 (100) NOT NULL,
        email VARCHAR2 (150) NOT NULL UNIQUE,
        phone VARCHAR2 (15),
        password VARCHAR2 (255) NOT NULL,
        role VARCHAR2 (50) DEFAULT 'user' NOT NULL,
        status VARCHAR2 (20) DEFAULT 'active' NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        reset_token VARCHAR2 (255),
        reset_expires TIMESTAMP,
        otp VARCHAR2 (10),
        otp_expires TIMESTAMP,
        refresh_token VARCHAR2 (500),
        is_verified NUMBER (1) DEFAULT 0
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    trusted_devices (
        id NUMBER GENERATED ALWAYS AS IDENTITY,
        user_email VARCHAR2 (255),
        device_token VARCHAR2 (255),
        user_agent VARCHAR2 (500),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        expires_at TIMESTAMP
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    company (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_code VARCHAR2 (30) NOT NULL UNIQUE, -- e.g. CMP-20250321-042
        company_name VARCHAR2 (200) NOT NULL,
        gst VARCHAR2 (50), -- GST number
        address VARCHAR2 (500),
        phone VARCHAR2 (50),
        admin_name VARCHAR2 (100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    lab (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lab_code VARCHAR2 (30) NOT NULL UNIQUE, -- e.g. LAB-20250321-015
        lab_name VARCHAR2 (200) NOT NULL,
        gst VARCHAR2 (50),
        address VARCHAR2 (500),
        phone VARCHAR2 (50),
        admin_name VARCHAR2 (100),
        lab_type VARCHAR2 (20) CHECK (lab_type IN ('internal', 'thirdparty')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    product (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_name VARCHAR2 (200) NOT NULL,
        product_id VARCHAR2 (100) NOT NULL UNIQUE, -- auto-generated on frontend (SMP-YYYYMMDD-XXX)
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    tests (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        test_name VARCHAR2 (100) NOT NULL UNIQUE
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    test_fields (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        test_id NUMBER,
        field_name VARCHAR2 (100),
        label VARCHAR2 (200),
        placeholder VARCHAR2 (200),
        FOREIGN KEY (test_id) REFERENCES tests (id)
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
CREATE TABLE
    test_results (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sample_id NUMBER, -- optional (if linked to sample)
        test_id NUMBER,
        field_id NUMBER,
        value VARCHAR2 (500),
        FOREIGN KEY (test_id) REFERENCES tests (id),
        FOREIGN KEY (field_id) REFERENCES test_fields (id)
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
-- TRF ka main record (Cards 1, 2, 3, 5)
CREATE TABLE
    trf_requests (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trf_code VARCHAR2 (50) NOT NULL UNIQUE, -- e.g. TRF-20250421-001
        -- Card 1: Company
        company_id NUMBER NOT NULL,
        request_name VARCHAR2 (200) NOT NULL,
        -- Card 2: Lab
        lab_id NUMBER NOT NULL,
        -- Card 3: Product
        product_id NUMBER NOT NULL,
        lot_no VARCHAR2 (100),
        -- Card 5: Remark
        remark VARCHAR2 (1000),
        -- Status tracking
        status VARCHAR2 (20) DEFAULT 'not_filled' CHECK (status IN ('not_filled', 'filled')),
        created_by VARCHAR2 (100), -- admin ka naam/id
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP,
        FOREIGN KEY (company_id) REFERENCES company (id),
        FOREIGN KEY (lab_id) REFERENCES lab (id),
        FOREIGN KEY (product_id) REFERENCES product (id)
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
-- Card 4: Admin ne konse tests select kiye aur unke fields define kiye
-- Yeh "template" hai user ke liye
CREATE TABLE
    trf_selected_tests (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trf_id NUMBER NOT NULL,
        test_id NUMBER NOT NULL, -- tests table se
        FOREIGN KEY (trf_id) REFERENCES trf_requests (id) ON DELETE CASCADE,
        FOREIGN KEY (test_id) REFERENCES tests (id)
    );

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / /
-- Har test ke andar konse fields honge (predefined + custom dono)
CREATE TABLE
    trf_test_fields (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trf_selected_id NUMBER NOT NULL, -- trf_selected_tests se
        field_id NUMBER, -- test_fields se (predefined ke liye)
        custom_label VARCHAR2 (200), -- custom field ka naam
        placeholder VARCHAR2 (200),
        is_predefined NUMBER (1) DEFAULT 1, -- 1 = predefined, 0 = custom
        sort_order NUMBER DEFAULT 0,
        -- User ka filled value (Phase 2 mein aayega)
        field_value VARCHAR2 (500),
        filled_at TIMESTAMP,
        FOREIGN KEY (trf_selected_id) REFERENCES trf_selected_tests (id) ON DELETE CASCADE,
        FOREIGN KEY (field_id) REFERENCES test_fields (id)
    );